_target_: graph_attention.tasks.DiffusionDenoisingTask
state_fields:
  - rho
  - rhou
  - rhov
  - rhow
  - rhoE
conditioning_parameters: []
physical_nondimensionalization: true
timesteps: 1000
cosine_s: 0.008
validation_seed: 1234
